controllers:
  resource: ../src/Controller/
  type: attribute
  prefix: /api/v1
  name_prefix: api_v1_

api_login_check:
  path: /api/v1/auth/login/email
  methods: [ POST ]

api_refresh_token:
  path: /api/token/refresh
