name: Merge Release into main

on:
  push:
    branches:
      - 1.x

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: main
          pr_title: "[Automated] Merge ${{ github.ref_name }} into main"
          pr_body: "Automated Pull Request"
          pr_reviewer: "imdhemy"
          pr_assignee: "imdhemy"

      - name: Enable auto-merge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
